[workspace]
members = [
    "httpserver/rust",
    "httpclient/rust",
    "keyvalue/rust",
    "logging/rust",
    "messaging/rust",
    "numbergen/rust",
    "testing/rust",
    # examples
    "factorial/rust",
]
